version: '3.8'
services:
  app:
    build: .
    ports:
      - 8000:8000
      - 7860:7860
    restart: always
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    restart: always

volumes:
  ollama: