# Generated by Django 3.2.25 on 2024-06-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_id', models.IntegerField(unique=True)),
                ('advice_text', models.TextField()),
                ('context', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('chat_text', models.TextField()),
                ('interaction_context', models.TextField(max_length=255)),
                ('victim', models.TextField(max_length=255)),
                ('culprit', models.TextField(max_length=255)),
                ('manipulation_strategy', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prolific_id', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text_feedback', models.TextField()),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.advice')),
            ],
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='advice',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.chat'),
        ),
    ]
