# Generated by Django 3.2.25 on 2024-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20240610_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_chat',
            field=models.CharField(choices=[('mistreated', 'I would feel mistreated'), ('wrong', 'I would feel like I might have done something wrong'), ('neutral', 'I would feel neutral, there is nothing wrong with this conversation')], default='none', max_length=20),
            preserve_default=False,
        ),
    ]
